# Generated by Django 4.1.3 on 2022-11-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='social_names',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
