# Generated by Django 4.1.3 on 2022-11-13 12:29

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_link_social_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='static/img')),
                ('description', models.TimeField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
