# Generated by Django 4.1.3 on 2022-11-15 12:09

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_alter_blog_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_slug', models.SlugField(max_length=30)),
                ('image_size', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='static/img')),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsite.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
